### ISSUE TITLE
Define graph ADT

### ISSUE THREAD

**Issue by jmcph4** [jmcph4/enceladus#16]
# Description #
The graph ADT represents the graph from mathematics and is a collection of vertices and edges connecting pairs of vertices.

Our definition of a graph includes multigraphs, so parallel edges and loops are allowed. This particular ADT is undirected.

# Tasks #
 - [ ] Add `graph` module
 - [ ] Add `Graph` trait
 - [ ] Implement `get_vertex`
 - [ ] Implement `get_mut_vertex`
 - [ ] Implement `set_vertex`
 - [ ] Implement `get_edge`
 - [ ] Implement `get_mut_edge`
 - [ ] Implement `set_edge`
 - [ ] Implement `insert_vertex`
 - [ ] Implement `remove_vertex`
 - [ ] Implement `insert_edge`
 - [ ] Implement `remove_edge`
 - [ ] Implement `order`
 - [ ] Implement `size`
 - [ ] Implement `degree`
 - [ ] Implement `is_adjacent`
 - [ ] Implement `is_incident`
 - [ ] Implement `neighbours`
 - [ ] Implement `endpoints`
 - [ ] Implement `clear`
