### ISSUE TITLE
Add benchmarks for `HashMap`

### ISSUE THREAD

**Issue by jmcph4** [jmcph4/enceladus#17]
# Description #
The `HashMap` hash table implementation should be benchmarked via [Criterion](
https://crates.io/crates/criterion).

# Tasks #
 - [x] Add Criterion
 - [ ] Write sequential insertion benchmark
 - [ ] Write random insertion benchmark
 - [ ] Write key search benchmark
 - [ ] Write value search benchmark
 - [ ] Write random, mixed-workload benchmark
