### ISSUE TITLE
Graph ADT should return references, not values

### ISSUE THREAD

**Issue by jmcph4** [jmcph4/enceladus#19]
# Description #
Currently, the `Graph` trait (which defines the graph ADT), has getters which return the actual underlying values within the collection, rather than references (either immutable or mutable) to them.

# Tasks #
 - [ ] Fix `get_vertex`
 - [ ] Fix `get_mut_vertex`
 - [ ] Fix `get_edge`
 - [ ] Fix `get_mut_edge`
