### ISSUE TITLE
Define map ADT

### ISSUE THREAD

**Issue by jmcph4** [jmcph4/enceladus#6]
# Description #

# Tasks #
 - [x] Define `Map` trait
 - [x] Implement `get`
 - [x] Implement `set`
 - [x] Implement `remove`
 - [x] Implement `size`
 - [x] Implement `contains_key`
 - [x] Implement `contains_value`
 - [x] Implement `clear`
